FROM node:14 AS app-base
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
RUN npm run build:ssr -S
RUN npm prune --production -S

FROM node:14 AS app-ui-ssr
ARG CONTAINER_PORT_UI_SSR
EXPOSE $CONTAINER_PORT_UI_SSR
WORKDIR /app
COPY --from=app-base /app/dist dist
