FROM node:14-alpine AS app-base
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
RUN npm run deph:graph
RUN npm run build:api -S
RUN npm prune --production -S

FROM node:14-alpine AS app-api
ARG CONTAINER_PORT_API
EXPOSE $CONTAINER_PORT_API
WORKDIR /app
COPY --from=app-base /app/node_modules /app/node_modules
COPY --from=app-base /app/dist/apps/api .
