export const CANDIDATES = [
  { name: 'Nathalie ARTHAUD', party: 'Lutte ouvrière' },
  { name: 'François ASSELINEAU', party: 'UPR' },
  { name: 'Nicolas DUPONT-AIGNAN', party: 'Debout la France' },
  { name: 'Anne HIDALGO', party: 'Parti socialiste' },
  { name: 'Yannick JADOT', party: 'Europe écologie - Les Verts' },
  { name: 'Anasse KAZIB', party: 'Révolution permanente' },
  { name: 'Georges KUZMANOVIC', party: 'République souveraine' },
  { name: 'Jean LASSALLE', party: 'Sans étiquette' },
  { name: 'Marine LE PEN', party: 'Rassemblement national' },
  {
    name: 'Emmanuel MACRON', party: 'La République En Marche'
  },
  { name: 'Jean-Luc MÉLENCHON', party: 'La France insoumise' },
  { name: 'Valérie PÉCRESSE', party: 'Les Républicains' },
  { name: 'Philippe POUTOU', party: 'Nouveau Parti anticapitaliste' },
  { name: 'Fabien ROUSSEL', party: 'PCF' },
  { name: 'Hélène THOUY', party: 'Parti animaliste' },
  { name: 'Éric ZEMMOUR', party: 'Reconquête' },
  { name: 'Michel BARNIER', party: '-' },
  { name: 'Arnaud CHICHE', party: 'Santé en danger' },
  { name: 'Clara EGGER', party: 'Espoir RIC 2022' },
  { name: 'Gaspard KOENIG', party: 'Simple' },
  { name: 'Nicolas MIGUET', party: 'Sans étiquette' },
  { name: 'Christiane TAUBIRA', party: 'Sans étiquette' },
  { name: 'Corinne BÉKAERT', party: 'Osons la différence' },
  { name: 'Marie CAU', party: 'Sans étiquette' },
  { name: 'Philippe Célestin MARECHAL', party: 'Sans étiquette' },
  { name: 'Antoine MARTINEZ', party: 'Volontaires pour la France' },
  { name: 'Philippe MAZUEL', party: 'PArti des Citoyens Européens' },
  { name: 'Martin ROCCA', party: 'Constituante 2022' },
  { name: 'Josef SCHOVANEC', party: '-' },
  { name: 'Rafik SMATI', party: 'Objectif France' },
  { name: 'Bertrand FESSARD DE FOUCAULT', party: '-' },
  { name: 'Jean-Marc FORTANÉ', party: '-' },
  { name: 'Florian PHILIPPOT', party: 'Les Patriotes' },
  { name: 'Stéphanie RIVOAL', party: 'Agissons' },
  { name: 'Gildas VIEIRA', party: '-' },
  { name: 'Patrick COJAN', party: '-' },
  { name: 'François HOLLANDE', party: '-' },
  { name: 'Yaya LAM', party: '-' },
  { name: 'Emmanuelle MÉNARD', party: '-' },
  { name: 'Guillaume MEURICE', party: '-' },
  { name: 'Antoine WAECHTER', party: '-' },
  { name: 'Stéphane WENDLINGER', party: '-' }
]
