export const CANDIDATES = [
  { name: 'Nathalie Arthaud', party: 'Lutte ouvrière' },
  { name: 'François Asselineau', party: 'UPR' },
  { name: 'Nicolas Dupont-Aignan', party: 'Debout la France' },
  { name: 'Anne Hidalgo', party: 'Parti socialiste' },
  { name: 'Yannick Jadot', party: 'Europe écologie - Les Verts' },
  { name: 'Anasse Kazib', party: 'Révolution permanente' },
  { name: 'Georges Kuzmanovic', party: 'République souveraine' },
  { name: 'Jean Lassalle', party: 'Sans étiquette' },
  { name: 'Marine Le Pen', party: 'Rassemblement national' },
  { name: 'Emmanuel Macron', party: 'La République En Marche' },
  { name: 'Jean-Luc Mélenchon', party: 'La France insoumise' },
  { name: 'Valérie Pécresse', party: 'Les Républicains' },
  { name: 'Philippe Poutou', party: 'Nouveau Parti anticapitaliste' },
  { name: 'Fabien Roussel', party: 'PCF' },
  { name: 'Hélène Thouy', party: 'Parti animaliste' },
  { name: 'Éric Zemmour', party: 'Reconquête' },
  { name: 'Michel Barnier', party: '-' },
  { name: 'Arnaud Chiche', party: 'Santé en danger' },
  { name: 'Clara Egger', party: 'Espoir RIC 2022' },
  { name: 'Gaspard Koenig', party: 'Simple' },
  { name: 'Nicolas Miguet', party: 'Sans étiquette' },
  { name: 'Christiane Taubira', party: 'Sans étiquette' },
  { name: 'Corinne Békaert', party: 'Osons la différence' },
  { name: 'Marie Cau', party: 'Sans étiquette' },
  { name: 'Philippe Célestin Marechal', party: 'Sans étiquette' },
  { name: 'Antoine Martinez', party: 'Volontaires pour la France' },
  { name: 'Philippe Mazuel', party: 'Parti des Citoyens Européens' },
  { name: 'Martin Rocca', party: 'Constituante 2022' },
  { name: 'Josef Schovanec', party: '-' },
  { name: 'Rafik Smati', party: 'Objectif France' },
  { name: 'Bertrand Fessard De Foucault', party: '-' },
  { name: 'Jean-Marc Fortané', party: '-' },
  { name: 'Florian Philippot', party: 'Les Patriotes' },
  { name: 'Stéphanie Rivoal', party: 'Agissons' },
  { name: 'Gildas Vieira', party: '-' },
  { name: 'Patrick Cojan', party: '-' },
  { name: 'François Hollande', party: '-' },
  { name: 'Yaya Lam', party: '-' },
  { name: 'Emmanuelle Ménard', party: '-' },
  { name: 'Guillaume Meurice', party: '-' },
  { name: 'Antoine Waechter', party: '-' },
  { name: 'Stéphane Wendlinger', party: '-' }
];
